[build]
  publish = "dist"
  command = "npm run build" # Укажите, если используете сборку (например, с Vite или React)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[headers]]
for = "/src/main.jsx"
[headers.values]
Content-Type = "application/javascript"
